### ISSUE TITLE
file missing error?

### ISSUE THREAD

**Issue by amasawa** [thomassutter/MoPoE#1]
File "MoPoE/eval_metrics/sample_quality.py", line 16, in <module>
    import prd_score.prd_score as prd
ModuleNotFoundError: No module named 'prd_score'

**Comment by thomassutter** [comment]
Hi, could you provide more details?

**Comment by amasawa** [comment]
Hi, I think it is the ModuleNotFoundError arising from the missing file Because I cannot find the prd_score class in this repository.
`import prd_score.prd_score as prd`

**Comment by amasawa** [comment]
Dear Sutter, can u fix the issue?

**Comment by thomassutter** [comment]
Hi, I added the missing files. Can you let me know if it works?
(Sorry for my late reply, I was on vacation)

**Comment by thomassutter** [comment]
> Dear Sutter, can u fix the issue?

Did the latest changes solve the issue? In case so, I would close the issue
