### ISSUE TITLE
Confusion about PoE fusion

### ISSUE THREAD

**Issue by microcourier** [thomassutter/MoPoE#4]
Thanks for your great paper. I have a confusion about the PoE part and wonder if you can clarify it.

In the paper, Definition 1 shows that the posterior is made by PoE, but i don't realize how we did it.

I tried to find the answer in the code, and came down to [poe](https://github.com/thomassutter/MoPoE/blob/main/divergence_measures/mm_div.py#L13) 
It seems to be adding mus and vars but not product it,what is the meaning of it?

I would apologize if it's a naive question, since i just study ML for a short time,and i will  appreciate it if you could clarify it. 
Thank a lot.

**Comment by thomassutter** [comment]
Hi, you are looking at the correct location.
The referenced function follows the computation of the PoE for Gaussian distribution, which is possible in closed form.
Maybe also look here:
[product of two gaussian pdfs](https://math.stackexchange.com/questions/1112866/product-of-two-gaussian-pdfs-is-a-gaussian-pdf-but-product-of-two-gaussian-vari)
